[Greeter]
background=/usr/share/backgrounds/sequoia-sunrise.jpg
background-color=#000000
draw-user-backgrounds=false
draw-grid=false
show-hostname=false
show-power=true
show-keyboard=false
show-clock=true
show-quit=true
logo=/usr/share/backgrounds/47-logo.png
other-monitors-logo=/usr/share/backgrounds/47-logo.png
theme-name=WhiteSur-Dark
icon-theme-name=WhiteSur-dark
font-name=SF Pro Display 11
activate-numlock=true
